import { test, expect } from '@playwright/test'
import { setup, playerBar, userId } from './fixtures'

const sizes = [[1920,1080],[1440,900],[1366,768],[1024,768],[768,1024],[430,932],[390,844],[375,812],[360,800],[320,568]]
async function overflow(locator) {
  expect(await locator.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
}
async function centered(locator, minimum) {
  // Wait for the existing card/overlay entrance transform to settle.
  await expect.poll(async () => Math.round((await locator.boundingBox()).width * 10) / 10).toBeGreaterThanOrEqual(minimum)
  const result = await locator.evaluate(el => {
    const b = el.getBoundingClientRect(), i = el.querySelector('svg').getBoundingClientRect()
    return { w:b.width, h:b.height, x:Math.abs(b.x+b.width/2-i.x-i.width/2), y:Math.abs(b.y+b.height/2-i.y-i.height/2) }
  })
  expect(result.w).toBeGreaterThanOrEqual(minimum - .05)
  expect(result.h).toBeGreaterThanOrEqual(minimum - .05)
  expect(result.x).toBeLessThan(1)
  expect(result.y).toBeLessThan(1)
}
async function menuBounds(menu, width, height) {
  await expect(menu).toBeVisible()
  const b = await menu.boundingBox()
  expect(b.x).toBeGreaterThanOrEqual(0)
  expect(b.y).toBeGreaterThanOrEqual(0)
  expect(b.x+b.width).toBeLessThanOrEqual(width)
  expect(b.y+b.height).toBeLessThanOrEqual(height)
}
for (const [width,height] of sizes) {
  test(`compact heroes and player at ${width}x${height}`, async ({page}) => {
    test.setTimeout(60000)
    await page.setViewportSize({width,height})
    const {db,errors} = await setup(page,{seconds:180})
    db.music_tracks.forEach(t => { t.duration=180 })
    await page.goto('/')
    const home=page.locator('.home-hero')
    await expect(home.locator('.stat-tracks .stat-value')).toHaveText('3')
    await expect(home.locator('.stat-duration .stat-value')).toHaveText('9m')
    await overflow(home)
    await overflow(page.locator('html'))
    if(width>=1024) {
      const box=await home.boundingBox()
      expect(box.height).toBeLessThanOrEqual(620)
      const ys=await home.locator('.home-stat-item').evaluateAll(els=>els.map(e=>e.getBoundingClientRect().y))
      expect(Math.max(...ys)-Math.min(...ys)).toBeLessThan(2)
    }
    await home.screenshot({path:`audit/home-podcast-final/home-${width}.png`,animations:'disabled'})
    await home.locator('.home-btn-play').click()
    await expect(playerBar(page).getByTitle('Pause',{exact:true})).toBeVisible()
    await page.evaluate(()=>{window.heroAudio=window.testAudio.find(a=>a.src)})
    await home.locator('.home-btn-explore').click()
    await expect(page).toHaveURL(/\/music$/)
    const action=page.locator('.music-library .sv-more-button').first()
    await centered(action,width<768?44:40)
    await action.click()
    await menuBounds(page.locator('.v2-action-menu:popover-open'),width,height)
    await page.keyboard.press('Escape')
    await expect(page.locator('.v2-action-menu:popover-open')).toHaveCount(0)
    await playerBar(page).getByTitle('Open Now Playing',{exact:true}).click()
    const dialog=page.getByRole('dialog',{name:'Now playing',exact:true})
    await expect(dialog).toBeVisible()
    await expect(dialog.getByRole('button',{name:'Pause',exact:true})).toBeInViewport()
    await overflow(dialog)
    const more=dialog.locator('.sv-np-top-actions .sv-more-button')
    await centered(more,width<768?44:40)
    await more.click()
    await menuBounds(dialog.locator('.v2-action-menu:popover-open'),width,height)
    await page.keyboard.press('Escape')
    await expect(dialog).toBeVisible()
    await expect(dialog.locator('.v2-action-menu:popover-open')).toHaveCount(0)
    await dialog.screenshot({path:`audit/home-podcast-final/player-${width}.png`,animations:'disabled'})
    await dialog.getByRole('button',{name:'Queue',exact:true}).click()
    await dialog.locator('.sv-np-card-volume').scrollIntoViewIfNeeded()
    await expect(dialog.getByRole('slider',{name:'Volume',exact:true})).toBeInViewport()
    for(const trigger of await dialog.locator('.sv-queue-item .sv-more-button').all()) await centered(trigger,width<768?44:40)
    expect(await page.evaluate(()=>window.heroAudio===window.testAudio.find(a=>a.src))).toBe(true)
    await dialog.getByRole('button',{name:'Close',exact:true}).click()
    await expect(dialog).toHaveCount(0)
    await page.goto('/podcasts')
    const podcast=page.locator('.podcast-hero')
    await expect(podcast.locator('.stat-shows .stat-num')).toHaveText('1')
    await expect(podcast.locator('.stat-episodes .stat-num')).toHaveText('3')
    await expect(podcast.locator('.stat-time .stat-num')).toHaveText('9m')
    await expect(podcast.locator('.podcast-mic-image')).toBeVisible()
    expect(await podcast.locator('.podcast-mic-image').evaluate(el=>el.complete&&el.naturalWidth===480)).toBe(true)
    await overflow(podcast)
    await overflow(page.locator('html'))
    if(width>=1024) {
      expect((await podcast.boundingBox()).height).toBeLessThanOrEqual(620)
      const ys=await podcast.locator('.podcast-stat-card').evaluateAll(els=>els.map(e=>e.getBoundingClientRect().y))
      expect(Math.max(...ys)-Math.min(...ys)).toBeLessThan(2)
    }
    await podcast.screenshot({path:`audit/home-podcast-final/podcast-${width}.png`,animations:'disabled'})
    await podcast.locator('.podcast-btn-play').click()
    await expect(playerBar(page).getByTitle('Pause',{exact:true})).toBeVisible()
    await expect(podcast.locator('.podcast-waveform')).toHaveClass(/is-playing/)
    await podcast.locator('.podcast-btn-explore').click()
    await expect(page.locator('#podcast-catalog')).toBeInViewport()
    expect(errors).toEqual([])
  })
}
test('menus support keyboard, outside click and real queue actions',async({page})=>{
  await setup(page,{seconds:180})
  await page.goto('/music')
  const trigger=page.locator('.music-library .sv-more-button').first()
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.v2-action-menu:popover-open')).toBeVisible()
  await page.locator('h1').click()
  await expect(page.locator('.v2-action-menu:popover-open')).toHaveCount(0)
  await trigger.focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('button',{name:'Add to queue',exact:true})).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('status')).toContainText('Added to queue')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})
test('unknown duration and broken artwork are honest and safe',async({page})=>{
  const {db}=await setup(page)
  db.music_tracks.forEach(t=>t.cover_url='/broken-cover.png')
  db.episodes.forEach(t=>delete t.duration)
  await page.goto('/')
  await expect(page.locator('.stat-duration .stat-value')).toHaveText('—')
  await expect(page.locator('.artwork-image')).toHaveAttribute('src','/icons/icon.svg')
  await page.goto('/podcasts')
  await expect(page.locator('.stat-time .stat-num')).toHaveText('—')
})
test('reduced motion disables hero animation and pointer parallax',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await setup(page)
  await page.goto('/')
  await page.locator('.home-hero').hover()
  expect(await page.locator('.home-vinyl').evaluate(el=>getComputedStyle(el).animationName)).toBe('none')
  expect(await page.locator('.home-music-stage').evaluate(el=>getComputedStyle(el).transform)).toBe('none')
})

test('playlist and library menus fit every requested viewport',async({page})=>{
  test.setTimeout(90000)
  const {db}=await setup(page,{seconds:180})
  const id='55555555-5555-4555-8555-555555555555'
  db.playlists.push({id,user_id:userId,name:'My playlist',track_ids:db.music_tracks.map(t=>t.id),revision:0})
  await page.goto('/library?playlist='+id)
  for(const [width,height] of sizes) {
    await page.setViewportSize({width,height})
    await overflow(page.locator('.playlist-page'))
    const more=page.locator('.playlist-track .sv-more-button').first()
    await more.scrollIntoViewIfNeeded()
    await centered(more,width<768?44:40)
    await more.click()
    await menuBounds(page.locator('.v2-action-menu:popover-open'),width,height)
    await page.keyboard.press('Escape')
  }
  await page.locator('.playlist-track .sv-more-button').first().click()
  await page.locator('.v2-action-menu:popover-open').getByRole('button',{name:'Favorite',exact:true}).click()
  await page.keyboard.press('Escape')
  await page.goto('/library')
  const more=page.locator('.v2-media-row .sv-more-button').first()
  await centered(more,44)
  await more.click()
  await menuBounds(page.locator('.v2-action-menu:popover-open'),320,568)
})
