import { test, expect } from '@playwright/test'
import { setup, playerBar } from './fixtures'

test('Now Playing retains the singleton and all playback controls', async ({page}) => {
  test.setTimeout(60000)
  await page.setViewportSize({width:1440,height:900})
  const {db,errors}=await setup(page,{seconds:180,preferences:{volume:.35,shuffle:false,repeat:'none',autoplay:true}})
  db.music_tracks[0].synced_lyrics=[{start:0,end:90,text:'Real fixture lyric'},{start:90,end:180,text:'Second fixture line'}]
  db.music_tracks[1].cover_url='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="320" height="320"><rect width="320" height="320" fill="#249089"/></svg>')
  await page.goto('/music')
  await page.getByRole('button',{name:'Play Track 1',exact:true}).click()
  await expect(playerBar(page).getByTitle('Pause',{exact:true})).toBeVisible()
  await page.evaluate(()=>{window.originalAudio=window.testAudio.find(a=>a.src)})
  await playerBar(page).getByTitle('Open Now Playing',{exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Now playing',exact:true})
  await expect(dialog).toBeVisible()
  await expect(playerBar(page)).toBeHidden()
  await dialog.getByRole('button',{name:'Pause',exact:true}).click()
  await expect.poll(()=>page.evaluate(()=>window.originalAudio.paused)).toBe(true)
  await dialog.getByRole('slider',{name:'Playback position'}).press('ArrowRight')
  await expect.poll(()=>page.evaluate(()=>window.originalAudio.currentTime)).toBeGreaterThanOrEqual(5)
  await dialog.getByRole('slider',{name:'Volume',exact:true}).fill('0.42')
  await dialog.getByRole('button',{name:'Mute',exact:true}).click()
  await expect.poll(()=>page.evaluate(()=>window.originalAudio.volume)).toBe(0)
  await dialog.getByRole('button',{name:'Unmute',exact:true}).click()
  await expect.poll(()=>page.evaluate(()=>window.originalAudio.volume)).toBe(.42)
  await dialog.getByRole('button',{name:'Shuffle',exact:true}).click()
  await expect(dialog.getByRole('button',{name:'Shuffle',exact:true})).toHaveAttribute('aria-pressed','true')
  await dialog.getByRole('button',{name:'Shuffle',exact:true}).click()
  await dialog.getByRole('button',{name:'Repeat: none',exact:true}).click()
  await expect(dialog.getByRole('button',{name:'Repeat: all',exact:true})).toBeVisible()
  await dialog.getByRole('button',{name:'Repeat: all',exact:true}).click()
  await expect(dialog.getByRole('button',{name:'Repeat: one',exact:true})).toBeVisible()
  await dialog.getByRole('button',{name:'Repeat: one',exact:true}).click()
  await dialog.getByRole('button',{name:'Favorite',exact:true}).click()
  await expect(dialog.getByRole('button',{name:'Remove favorite',exact:true})).toHaveAttribute('aria-pressed','true')
  const beforeTabs=await page.evaluate(()=>window.originalAudio.currentTime)
  await dialog.getByRole('button',{name:'Lyrics',exact:true}).click()
  await expect(dialog.getByText('Real fixture lyric')).toBeVisible()
  await dialog.getByRole('button',{name:'Queue',exact:true}).click()
  expect(await page.evaluate(()=>window.originalAudio.currentTime)).toBe(beforeTabs)
  await dialog.getByRole('button',{name:'Move Track 1 down',exact:true}).click()
  await expect(dialog.locator('.v2-np-queue-meta strong').first()).toHaveText('Track 2')
  await dialog.getByRole('button',{name:'Play Track 2',exact:true}).click()
  await expect(dialog.locator('.sv-np-track-title')).toHaveText('Track 2')
  await expect(dialog.locator('.sv-np-layer-fadein')).toHaveAttribute('src',db.music_tracks[1].cover_url)
  await expect(dialog.locator('.sv-np-layer-fadeout')).toHaveCount(0)
  await dialog.getByRole('button',{name:'Next',exact:true}).click()
  await expect(dialog.locator('.sv-np-track-title')).toHaveText('Track 1')
  await dialog.getByRole('button',{name:'Previous',exact:true}).click()
  await expect(dialog.locator('.sv-np-track-title')).toHaveText('Track 2')
  await dialog.getByRole('button',{name:'Remove Track 3 from queue',exact:true}).click()
  await expect(dialog.locator('.sv-queue-item')).toHaveCount(2)
  await dialog.getByRole('button',{name:'Pause',exact:true}).click()
  await dialog.getByRole('slider',{name:'Playback position'}).press('ArrowRight')
  const time=await page.evaluate(()=>window.originalAudio.currentTime)
  await dialog.getByRole('button',{name:'Close',exact:true}).click()
  await expect(dialog).toHaveCount(0)
  await expect(playerBar(page)).toBeVisible()
  await playerBar(page).getByTitle('Open Now Playing',{exact:true}).click()
  await expect(dialog).toBeVisible()
  expect(await page.evaluate(()=>window.originalAudio.currentTime)).toBe(time)
  await expect(dialog.getByRole('slider',{name:'Volume',exact:true})).toHaveValue('0.42')
  await expect(dialog.locator('.sv-queue-item')).toHaveCount(2)
  await dialog.getByRole('button',{name:'Lyrics',exact:true}).click()
  await expect(dialog.getByText('No lyrics available for this track.')).toBeVisible()
  expect(await page.evaluate(()=>window.originalAudio===window.testAudio.find(a=>a.src))).toBe(true)
  expect(await page.evaluate(()=>window.testAudio.filter(a=>a.src).length)).toBe(1)
  expect(errors).toEqual([])
})

test('progress advances without rerendering the queue list',async({page})=>{
  await page.addInitScript(()=>{
    window.queueRenders=0
    window.__REACT_DEVTOOLS_GLOBAL_HOOK__={
      supportsFiber:true,renderers:new Map(),inject:()=>1,onCommitFiberUnmount:()=>{},
      onCommitFiberRoot:(_id,root)=>{
        const walk=node=>{
          if(!node)return
          const type=node.type?.type || node.type
          if((type?.name==='QueueList' || type?.name?.startsWith('QueueList')) && (node.flags&1)) window.queueRenders++
          walk(node.child);walk(node.sibling)
        }
        walk(root.current)
      }
    }
  })
  await setup(page,{seconds:180})
  await page.goto('/music')
  await page.getByRole('button',{name:'Play Track 1',exact:true}).click()
  await playerBar(page).getByTitle('Open Now Playing',{exact:true}).click()
  await expect(page.locator('.sv-np-queue-list')).toBeVisible()
  await expect.poll(()=>page.evaluate(()=>window.queueRenders)).toBeGreaterThan(0)
  const baseline=await page.evaluate(()=>({renders:window.queueRenders,time:window.testAudio.find(a=>a.src).currentTime}))
  await expect.poll(()=>page.evaluate(()=>window.testAudio.find(a=>a.src).currentTime)).toBeGreaterThan(baseline.time+2)
  expect(await page.evaluate(()=>window.queueRenders)).toBe(baseline.renders)
})

test('long queue scrolls inside panel, broken cover falls back',async({page})=>{
  await page.setViewportSize({width:1024,height:768})
  const {db}=await setup(page,{seconds:180})
  db.music_tracks=Array.from({length:80},(_,i)=>({...db.music_tracks[0],id:'long-'+i,title:'A long title with many words '+i,cover_url:'/missing.png'}))
  await page.goto('/music')
  await page.getByRole('button',{name:'Play A long title with many words 0',exact:true}).click()
  await playerBar(page).getByTitle('Open Now Playing',{exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Now playing',exact:true})
  await expect(dialog.locator('.sv-np-artwork-img')).toHaveAttribute('src','/icons/icon.svg')
  await expect(dialog.locator('.sv-np-layer-fadein')).toHaveAttribute('src','/icons/icon.svg')
  expect(await dialog.evaluate(el=>el.scrollHeight<=el.clientHeight+1)).toBe(true)
  const panel=dialog.locator('.sv-np-card-body')
  expect(await panel.evaluate(el=>el.scrollHeight>el.clientHeight)).toBe(true)
  await dialog.locator('.sv-queue-item').last().scrollIntoViewIfNeeded()
  await expect(dialog.getByRole('slider',{name:'Volume',exact:true})).toBeInViewport()
})
